# 欢迎使用Acrylic主题!🎉
# Welcome to use theme of Acrylic!🎉
# 文档: https://Acrylic.zhheo.com/
# dosc: https://Acrylic.zhheo.com/
# 交流群: 649565726
# 这是Dev版!
# -------------------------------------

# 图片 (image)
# -------------------------------------

# 网站图标 (Favicon)
favicon: https://tucdn.wpon.cn/2023/02/10/a43d4d587028e.png

# 头像 (Avatar)
avatar:
  img: https://p.zhheo.com/2023ab4befd994d9bc8e1e6a78027d517e21075402.png!cover
default_img:
default_title:
default_text:
# A simple 404 page
error_404:
  enable: true
  subtitle: '请尝试站内搜索寻找文章'
  background: https://tucdn.wpon.cn/2023/02/09/5fe538725e242.gif

# 即刻短文 (essay)
# ------------------------------------
essay:
  enable: true
  descr: 分享生活的小确幸
  tip: 使用 即刻短文静态部署版 构建
  link: /posts/49736/
  text: 如何使用
  icon: fas fa-circle-chevron-right

# 导航栏 (nav)
# ------------------------------------
nav:
  left_groups:
    enable: true
    group:
      - title: 博客
        a_item:
          - text: 主页
            link: https://zhheo.com/
            img: https://p.zhheo.com/20232e121c3fb2daa71897d26a515e030f49073402.png!cover_mini
            class: out
          - text: 博客
            link: /
            img: https://p.zhheo.com/20234681e06b8e086aa5b15481cb89fd38c7071002.png!cover_mini
            class: out
          - text: 图片博客
            link: https://plog.zhheo.com/
            img: https://p.zhheo.com/20236a16354d7c333cc7595efaee4b8c5667074602.png!cover_mini
            class: out
          - text: 开发博客
            link: https://apps.zhheo.com/
            img: https://p.zhheo.com/2023042bb31614949504f9ac59b134ce971d075802.png!cover_mini
            class: out
  logo: 
    enable: true
    class: i_class #i_class/text/img 
    custom: heoicon icon-heologo #Heo/https://xxx.com/logo.png
  fps_enable: false
  menu:
    文库:
      文章列表: /archives/ || fas fa-box-archive
      全部分类: /categories/ || fas fa-cube
      全部标签: /tags/ || fas fa-tags
      即刻短文: /essay/ || fas fa-bars-staggered
    专栏:
      设计报告: /tags/设计报告/ || fas fa-swatchbook
      设计分享: /tags/Heocan/ || fas fa-object-group
      设计工具: /tags/Sketch/ || fas fa-palette
      视频混剪: /tags/混剪/ || fas fa-scissors
    友链:
      友链鱼塘: /fcircle/ || fas fa-fish-fins
      友情链接: /link/ || fas fa-user-group
      宝藏博主: javascript:travelling() || fas fa-bus
    我的:
      在线工具: /tlink/ || fas fa-screwdriver-wrench
      电影推荐: /movies/ || fas fa-clapperboard
      关于本站: /about/ || fas fa-sailboat
  right_button:
    travelling: true
    random: true
    console: true

# 手机边栏 (sidebar)
# --------------------------------------
sidebar: 
  list_group: true
  tag: true

# 中控台 (console)
# --------------------------------------
console:
  comment: true
  tag: true
  archives: true 

# search (搜索)
# see 
# --------------------------------------

# Algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6

# Local search
local_search:
  enable: false
  preload: false
  CDN:

# Math (數學)
# --------------------------------------

# MathJax
mathjax:
  enable: false
  per_page: false

# KaTeX
katex:
  enable: false
  per_page: false
  hide_scrollbar: true


# about(关于页面)
# --------------------------------------
about:
  info:
    right:
      # - 🤖️ 数码爱好者
      # - 🔍 分享与热心帮助
      # - 🏠 智能家居小能手
      # - 🔨 开发小萌新
    left:
      # - 专修交互设计 🤝
      # - 脚踏实地行动派 🏃
      # - 专攻各种困难 🧱
      # - 人狠话不多 💢
  job: #学生、独立开发者、博主
  live: #中国，北京市
  born: #1997
  school: #大连工业大学
  can: #产品设计
  work: #UI/产品
  character: #逻辑学家
  character2: #INTP-T
  personalities: #https://cdn.zhheo.com/public/svg/INTP-T.svg
  selfie: #https://p.zhheo.com/202352d98ec86bef3388a0152b33cf9d06ad082002.png!cover
  maxim1: #荆棘之路，
  maxim2: #劈风斩浪。
  tc1: #玄学流电脑疑难问题
  tc2: #解决专家
  tc3: #软件学习能力
  tc4: #MAX
  uid: #'UID:125766904'
  fanjuname: #刺客伍六七
  fanjulink: #'https://www.bilibili.com/bangumi/play/ss36594/?spm_id_from=333.999.0.0'
  liketechnology: #数码科技
  liketechnologyand: #手机、电脑软硬件
  sllctitle: #为什么建站？
  xllc: #创建这个站的时候，想要就是能够有一个自己能够积累知识、积累兴趣的地方。和他人分享，会让这些成为积累和沉淀。如果能够帮助到更多的人，帮助更多人解决问题，那一定是非常棒的事情。分享这件事我从很早就开始了，起初做的微信公众号，现在做的网站。因为我比较喜欢研究数码和软件，想要探究在互联网上的事物是如何被创造和发展。网络给我带来了非常多的知识和眼界，我也想力所能及的分享一些我生活的琐碎知识。与大多数垂直类的技术博客不同，这里的种类会非常的繁杂，有技能的教程干货、有生活上的吐槽和妙招、有话题上的思考和想法。一般我研究什么、发现了什么都会分享在这里。这些就是创造这个小站的本意，也是我分享生活的方式。有幸能和你相遇在这里，相信我们能共同留下一段美好记忆。


# wordcount (字數統計)
wordcount:
  enable: false
  post_wordcount: true
  min2read: true
  total_wordcount: true


# 文章 (Post)
# --------------------------------------

# 版权信息 (copyright)
# --------------------------------------
copyright:
  enable: true
  link: /cc/
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 阅读建议 (Related Articles)
related_post:
  enable: true

post_meta:
  page: # Home Page
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

# ptool（文章底部工具）
# --------------------------------------
ptool:
  enable: true

# 打赏
reward:
  enable: true
  QR_code:
    - img: https://acrylic.leonus.cn/i/2023/02/19/ddz6gd.webp
      link:
      text: 微信
    - img: https://acrylic.leonus.cn/i/2023/03/04/pmf2ec.webp
      link:
      text: 爱发电



# Comments System
# --------------------------------------

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Waline/Twikoo/Artalk
  use: Twikoo # Waline/Twikoo/Artalk
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: false # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page

# waline - A simple comment system with backend support fork from Valine
# https://waline.js.org/
waline:
  serverURL: # Waline server address url
  bg: # waline background
  pageview: false
  option:

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://photoimage.2lc.top
  region:
  visitor: false
  option:

# Artalk
# https://artalk.js.org/guide/frontend/config.html
artalk:
  server:
  site:
  visitor: false
  option:

# Footer
# --------------------------------------
footer:
  footer_icons:
    enable: true
    left:
      - icon: fa-solid fa-compass
        link: https://www.marcus233.top/
        desrc: 个人主页
        class: out
      - icon: fa-brands fa-qq
        link: https://res.abeim.cn/api/qq/?qq=3105950984
        desrc: 联系QQ
        class: out
      - icon: fa-brands fa-weixin
        link: /wechat/
        desrc: 联系微信
        class: in
      - icon: fa-solid fa-envelope
        link: mailto:marcus@marcus233.top
        desrc: 发送邮件
        class: out
    right:
      - icon: fa-brands fa-github
        link: https://github.com/Marcusyyds
        desrc: Github主页
        class: out
      - icon: fa-brands fa-bilibili
        link: https://space.bilibili.com/1024450661
        desrc: 哔哩哔哩主页
        class: out
      - icon: fa-solid fa-star
        link: /stars/
        desrc: 藏宝阁
        class: in
      - icon: fa-solid fa-comment
        link: /message/
        desrc: 留言
        class: in
  footer_logo:
    enable: true
    url: https://bu.dusays.com/2023/03/03/6401a7960c0fb.webp
  footer_group:
    enable: true
    footer_group_link:
      - group_title: 软件
        footer_links: 
          - text: 敲木鱼
            link: /stars/
            class: in
          - text: 轻节食
            link: /sentence/
            class: in
          - text: DelSpace3
            link: /zone/
            class: in
          - text: 比例计
            link: /fcircle/
            class: in
      - group_title: 产品
        footer_links: 
          - text: 设计报告
            link: /about/
            class: in
          - text: 优质报告
            link: /atom.xml
            class: in
      - group_title: 设计
        footer_links: 
          - text: Heocan
            link: /categories/博客相关
            class: in
          - text: Sketch
            link: /categories/生活点滴
            class: in 
          - text: 设计报告
            link: /categories/资源分享
            class: in
          - text: Photoshop
            link: /categories/学习笔记
            class: in
      - group_title: 开发
        footer_links: 
          - text: Hexo魔改
            link: /categories/博客相关
            class: in
          - text: Swift开发
            link: /categories/生活点滴
            class: in 
          - text: 网页前端
            link: /categories/资源分享
            class: in
      - group_title: 生活
        footer_links: 
          - text: 音乐榜单
            link: /music/
            class: in
          - text: 我的电影
            link: /categories/生活点滴
            class: in 
          - text: 读书笔记
            link: /categories/资源分享
            class: in
          - text: 视频剪辑
            link: /categories/学习笔记
            class: in
      - group_title: 导航
        footer_links: 
          - text: 即刻短文
            link: /categories/博客相关
            class: in
          - text: 在线工具
            link: /categories/生活点滴
            class: in 
          - text: 友链文章
            link: /categories/资源分享
            class: in
      - group_title: 服务
        footer_links: 
          - text: 51la统计
            link: /categories/博客相关
            class: in
          - text: BlogFinder
            link: /categories/生活点滴
            class: in 
          - text: 十年之约
            link: /categories/资源分享
            class: in
      - group_title: 协议
        footer_links: 
          - text: 隐私协议
            link: /categories/博客相关
            class: in
          - text: Cookies
            link: /categories/生活点滴
            class: in 
          - text: 版权协议
            link: /categories/资源分享
            class: in
  icp: 京ICP备1905135号


# hometop
# --------------------------------------
hometop:
  enable: true
  banner:
    enable: true
    class: creativity #people/creativity
    title_up: 分享设计
    title_dn: 与科技生活
    tips: ZHHEO.COM
  categoryGroup:
    enable: true
    category_list:
      - name: 必看精选
        path: /tags/必看/
        shadow: var(--heo-shadow-blue)
        class: bikan
        icon: fas fa-dove
      - name: 热门文章
        path: /tags/热门/
        shadow: var(--heo-shadow-red)
        class: remen
        icon: fas fa-burn
      - name: 实用教程
        path: /tags/教程/
        shadow: var(--heo-shadow-green)
        class: shiyong
        icon: fas fa-book
  topgroup:
    enable: true
    class: both #card/post/both
    #如果为both则都填
    #如果为card
    card:
      tips: 强势回归
      title: Acrylic-Promote
      bg: https://acrylic.leonus.cn/i/2023/03/04/ir6ary.webp
      link: https://blog.zhheo.com/p/671f98c8.html
      buttontext: 更多推荐
      icon: fas fa-circle-plus
    #如果为post
    post:
      class: 
      number: 6

# 广告 (ad)
# --------------------------------------
ad:
  index:
  aside:
  post:

# Beautify/Effect (美化/效果)
# --------------------------------------

# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!

theme_color:
  enable: true
  main: "#425AEF"
#   paginator: "#00c4b6"
  button_hover: "#425AEF"
#   text_selection: "#00c4b6"
  link_color: "#425AEF"
#   meta_color: "#858585"
#   hr_color: "#A4D8FA"
#   code_foreground: "#F47466"
#   code_background: "rgba(27, 31, 35, .05)"
#   toc_color: "#00c4b6"
#   blockquote_padding_color: "#49b1f5"
#   blockquote_background_color: "#49b1f5"
#   scrollbar_color: "#49b1f5"
#   meta_theme_color_light: "ffffff"
#   meta_theme_color_dark: "#0d0d0d"


# 默认显示模式 (Default display mode)
# light (default) / dark
display_mode: light


# 加载动画 (Loading)
# --------------------------------------
loading: 
  enable: true

# 侧边栏 (aside)
# --------------------------------------

aside:
  enable: true
  button: true
  mobile: true # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/xxxxxx
  card_weixin:
    enable: true
  card_recent_post:
    enable: false
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_all_info:
    enable: true
    post_count: true
    runtime: true
    word_count: true
# busuanzi count for PV / UV in site
# 訪問人數
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# Time difference between publish date and now (網頁運行時間)
# Formal: Month/Day/Year Time or Year/Month/Day Time
runtimeshow:
  enable: true
  publish_date: 

# Bottom right button (右下角按鈕)
# --------------------------------------

# Conversion between Traditional and Simplified Chinese (簡繁轉換)
translate:
  enable: true
  # The text of a button
  default: 繁
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chinese）
  defaultEncoding: 2
  # Time delay
  translateDelay: 0
  # The text of the button when the language is Simplified Chinese
  msgToTraditionalChinese: '繁'
  # The text of the button when the language is Traditional Chinese
  msgToSimplifiedChinese: '簡'

# Read Mode (閲讀模式)
readmode: false

# dark mode
darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically (自動切換 dark mode和 light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: 1

# Don't modify the following settings unless you know how they work (非必要請不要修改 )
# Choose: readmode,translate,darkmode,hideAside,toc,chat,comment
# Don't repeat 不要重複
rightside_item_order:
  enable: false
  hide: # readmode,translate,darkmode,hideAside
  show: # toc,chat,comment

# Lightbox (圖片大圖查看模式)
# --------------------------------------

# fancybox
# http://fancyapps.com/fancybox/3/
fancybox: true

# Tag Plugins settings (標籤外掛)
# --------------------------------------

# mermaid
# see https://github.com/mermaid-js/mermaid
mermaid:
  enable: false
  # built-in themes: default/forest/dark/neutral
  theme:
    light: default
    dark: dark

# Note (Bootstrap Callout)
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# other
# --------------------------------------

# Pjax
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
  enable: true
  exclude:
    # - xxxx
    # - xxxx

# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: true
  per_page: true

# Snackbar (Toast Notification 彈窗)
# https://github.com/polonel/SnackBar
# position 彈窗位置
# 可選 top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: top-center
  bg_light: '#49b1f5' # The background color of Toast Notification in light mode
  bg_dark: '#1f1f1f' # The background color of Toast Notification in dark mode

# https://instant.page/
# prefetch (預加載)
instantpage: true

# https://github.com/vinta/pangu.js
# Insert a space between Chinese character and English character (中英文之間添加空格)
pangu:
  enable: false
  field: site # site/post

# Lazyload (圖片懶加載)
# https://github.com/verlok/vanilla-lazyload
lazyload:
  enable: false
  field: site # site/post
  placeholder:
  blur: false

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
# pwa:
#   enable: false
#   manifest: /pwa/manifest.json
#   apple_touch_icon: /pwa/apple-touch-icon.png
#   favicon_32_32: /pwa/32.png
#   favicon_16_16: /pwa/16.png
#   mask_icon: /pwa/safari-pinned-tab.svg

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta: true

# Add the vendor prefixes to ensure compatibility
css_prefix: true

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    - <script type="text/javascript" src="https://cdn1.tianli0.top/npm/jquery@latest/dist/jquery.min.js"></script>
    - <script src="//cdn.bootcss.com/pace/1.0.2/pace.min.js"></script>
    - <script src="/js/blogex.js"></script>
    - <script src="/js/black.js"></script>
    - <script src="/js/xh.js"></script>
    - <script src="/js/nav.js"></script>
    - <script src="/js/bblist.js"></script>
    - <script data-pjax src="https://npm.elemecdn.com/anzhiyu-blog@1.1.6/js/swiper.min.js"></script>
    - <script async data-pjax src="/js/jkdw.js"></script>
    - <script async data-pjax src="/js/waterfall.js"></script>
    - <script src="/js/nav2.js"></script>
    - <script src="/js/heo.js"></script>
    - <script src="/js/hidescrollbar.js"></script>
    - <script src="/js/rightmenu.js"></script>
    - <script src="/js/sayhi.js"></script>
    - <script async data-pjax src="/js/anzhiyu.js"></script>
    - <script async data-pjax src="/js/anzhiyufunction.js"></script>
    - <script async src="/js/anzhiyuOnlyOne.js"></script>
    - <script src="/heo/random.js"></script>
    

# CDN
# Don't modify the following settings unless you know how they work
# 非必要請不要修改
CDN:
  # The CDN provider of internal scripts (主題內部 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( dev版的主題只能設置為 local )
  internal_provider: local

  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: moezz/local/jsdelivr/unpkg/cdnjs/custom
  # when set it to local, you need to install hexo-butterfly-extjs
  third_party_provider: jsdelivr

  # Add version number to CDN, true or false  
  version: false

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
    # main_css:
    countup_js: /js/countup.js
    # main:
    # utils:
    # translate:
    # local_search:
    # algolia_js:
    # algolia_search_v4:
    # instantsearch_v4:
    # pjax:
    twikoo: https://cdn2.tianli0.top/gh/zhheo/twikoo@dev/dist/twikoo.all.min.js
    # waline_js:
    # waline_css:
    # mathjax:
    # katex:
    # katex_copytex:
    # mermaid:
    # lazyload:
    # instantpage:
    # typed:
    # pangu:
    # fancybox_css_v4:
    # fancybox_v4:
    # snackbar_css:
    # snackbar:
    # activate_power_mode:
    fontawesomeV6: https://cdn1.tianli0.top/npm/@fortawesome/fontawesome-free/css/all.min.css
    aplayer_css: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.css
    aplayer_js: https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.js
    meting_js: https://cdn1.tianli0.top/gh/hexo-theme-Acrylic/JS-Acrylic@main/Meting.js
    # artalk_js:
    # artalk_css:
